### ISSUE TITLE
Unable to build pangraph

### ISSUE THREAD

**Issue by sumit-walia** [neherlab/pangraph#54]
Hello, I am encountering the following error when attempting to build the pangraph on a monkeypox dataset. I am using this command: `pangraph build in.fa`

`ERROR: BoundsError: attempt to access 1-element Vector{PanGraph.Graphs.Align.Clade} at index [2]` 

I would greatly appreciate any assistance.

Thanks,
Sumit

**Comment by mmolari** [comment]
Hello Sumit,
thank you for pointing that out. Could you provide more information on the error? If you'd have a way to share the dataset I could try to reproduce it on my end. Otherwise could you share more details on the error? It would be important to have the full error message, for me to better understand where the algorithm is failing.
Cheers,
Marco

**Comment by liampshaw** [comment]
I think I've encountered this before - the error message isn't helpful and should probably be fixed, but my guess is that you have an empty line in your input fasta `in.fa` as below:

```
>1
AAGAGAACACACACTGACTGA

>2 
ACATCATCGTCAGTACGATCGATCGA
```

This can arise if you generate `in.fa` with `cat *.fa > in.fa` depending on the end of each file. If you delete the empty lines it should work I hope - let us know how you get on!

**Comment by sumit-walia** [comment]
Thanks, @liampshaw and @mmolari for the comments. The issue was indeed due to an empty line at the end of the file.

**Comment by mmolari** [comment]
Thanks @liampshaw! And thanks @sumit-walia for pointing it out. I'll combine this with #47 and add a small sanity check on the input to avoid confusion in the future.
