### ISSUE TITLE
Non-boolean error in pangraph export

### ISSUE THREAD

**Issue by conmeehan** [neherlab/pangraph#59]
Hi,

I am getting the following error when I run the latest Pangraph:
julia --threads 15 --project=. src/PanGraph.jl export --no-duplications --export-panX --output-directory pangraph_export pangraph.json

Aligning blocks. Building trees...  74%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                    |  ETA: 0:55:55
ERROR: LoadError: TypeError: non-boolean (Missing) used in boolean context
Stacktrace:
  [1] find_midpoint(t::TreeTools.Tree{TreeTools.EmptyData}; topological::Bool)
    @ TreeTools /mnt/storage/conda/cmeehan/pangraph/share/julia/packages/TreeTools/wxYIX/src/methods.jl:721
  [2] root_midpoint!(t::TreeTools.Tree{TreeTools.EmptyData}; topological::Bool)
    @ TreeTools /mnt/storage/conda/cmeehan/pangraph/share/julia/packages/TreeTools/wxYIX/src/methods.jl:625
  [3] #root!#32
    @ /mnt/storage/conda/cmeehan/pangraph/share/julia/packages/TreeTools/wxYIX/src/methods.jl:611 [inlined]
  [4] (::Main.PanGraph.PanX.var"#13#14"{TreeTools.Tree{TreeTools.EmptyData}})()
    @ Main.PanGraph.PanX /mnt/storage/tools/pangraph/src/panX.jl:122
  [5] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging ./logging.jl:511
  [6] with_logger
    @ ./logging.jl:623 [inlined]
  [7] produce_tree(alignment::String, scale::Int64)
    @ Main.PanGraph.PanX /mnt/storage/tools/pangraph/src/panX.jl:121
  [8] emitblock(block::Main.PanGraph.Graphs.Blocks.Block, root::String, prefix::String, identifier::Main.PanGraph.PanX.var"#11#12"{Dict{Main.PanGraph.Graphs.Nodes.Node, String}}; reduced::Bool)
    @ Main.PanGraph.PanX /mnt/storage/tools/pangraph/src/panX.jl:160
  [9] emit(G::Main.PanGraph.Graphs.Graph, root::String)
    @ Main.PanGraph.PanX /mnt/storage/tools/pangraph/src/panX.jl:283
 [10] (::Main.PanGraph.var"#43#48")(args::Vector{String})
    @ Main.PanGraph /mnt/storage/tools/pangraph/src/export.jl:173
 [11] run(cmd::Main.PanGraph.Commands.Command, args::Vector{String})
    @ Main.PanGraph.Commands /mnt/storage/tools/pangraph/src/args.jl:182
 [12] main(args::Vector{String})
    @ Main.PanGraph /mnt/storage/tools/pangraph/src/PanGraph.jl:162
 [13] top-level scope
    @ /mnt/storage/tools/pangraph/src/PanGraph.jl:179
in expression starting at /mnt/storage/tools/pangraph/src/PanGraph.jl:1

I had run exactly the same dataset through pangraph export before (around 4 months ago) and it worked fine so seems to be a problem with the latest version. Any advice you have on how to fix would be great.

Thanks,
Conor

**Comment by conmeehan** [comment]
Hi Marco,

Sure, a smaller one that still fails in the same way is attached. I had run these exact files through pangraph before so I agree seems that its a TreeTools issue. I am looking just for the geneCluster.json file that is created, not the rest of the tree etc, so if there was a way to compute only this and not the whole tree, that might be a workaround? It would also reduce my runtime considerably!

Cheers,
Conor
[testMTBC_pangraph.json.zip](https://github.com/neherlab/pangraph/files/12406653/testMTBC_pangraph.json.zip)

**Comment by mmolari** [comment]
Thanks, I'll be testing it and see if I can find the cause of the error. You're right, the long run time is probably due to tree building for very long blocks. In the meantime if you only need general properties of the `geneCluster.json` file, I can suggest this python package: [pypangraph](https://github.com/mmolari/pypangraph). This allows you to load the graph and directly extract general properties. In particular in [this section](https://github.com/mmolari/pypangraph#other-pangraph-representation) it is shown how to export the graph as pandas dataframes with general block statistics (`pan.to_blockstats_df()`) or as a presence/absence matrix of blocks (`pan.to_blockcount_df()`).
Hope this helps in the meantime!
Marco

**Comment by conmeehan** [comment]
Ok thanks, appreciated. I do indeed just want a presence/absence matrix (and was creating it myself with python) so that might be what I need instead. Thanks! Hopefully the error is easy to find and fix.

**Comment by mmolari** [comment]
Happy that it helps! It should be considerably faster.
Concerning the error, I looked into it and it is an issue with midpoint rooting in TreeTools, caused by a numerical approximation error. I opened an [issue](https://github.com/PierreBarrat/TreeTools.jl/issues/41) and will update PanGraph soon with a fix.
Thanks again for the feedback!
Marco

**Comment by mmolari** [comment]
Just a small update: I updated TreeTools to include @PierreBarrat's fix, and then tested pangraph on the test set provided, and this solved the error for me. I released a new minor version of pangraph that includes this fix.

**Comment by conmeehan** [comment]
It worked on the test set so tentatively I think we are good to go. Thanks so much.
